name: dockerfile-language-server
version: 0.15.0
description: Language server for Dockerfiles powered by Node, TypeScript, and VSCode
homepage: https://github.com/rcjsuen/dockerfile-language-server
license: MIT
url: {}
sha256: {}
sha512: {}
signature: {}
source_url: ""
source_sha256: ""
source_sha512: ""
install:
    type: archive
    binary_name: ""
    strip_components: 2
    format: tar.gz
post_install: ""
dependencies:
    - node
keg_only: false
bottle:
    darwin_amd64:
        url: https://ghcr.io/v2/homebrew/core/dockerfile-language-server/blobs/sha256:7e63595a7c55824a185f84aeef01ba0c0ad797c217fcbabd23a0990614ff7795
        sha256: 7e63595a7c55824a185f84aeef01ba0c0ad797c217fcbabd23a0990614ff7795
        sha512: ""
        signature: ""
    darwin_arm64:
        url: https://ghcr.io/v2/homebrew/core/dockerfile-language-server/blobs/sha256:7e63595a7c55824a185f84aeef01ba0c0ad797c217fcbabd23a0990614ff7795
        sha256: 7e63595a7c55824a185f84aeef01ba0c0ad797c217fcbabd23a0990614ff7795
        sha512: ""
        signature: ""
    linux_amd64:
        url: https://ghcr.io/v2/homebrew/core/dockerfile-language-server/blobs/sha256:7e63595a7c55824a185f84aeef01ba0c0ad797c217fcbabd23a0990614ff7795
        sha256: 7e63595a7c55824a185f84aeef01ba0c0ad797c217fcbabd23a0990614ff7795
        sha512: ""
        signature: ""
    linux_arm64:
        url: https://ghcr.io/v2/homebrew/core/dockerfile-language-server/blobs/sha256:7e63595a7c55824a185f84aeef01ba0c0ad797c217fcbabd23a0990614ff7795
        sha256: 7e63595a7c55824a185f84aeef01ba0c0ad797c217fcbabd23a0990614ff7795
        sha512: ""
        signature: ""
source:
    url: https://registry.npmjs.org/dockerfile-language-server-nodejs/-/dockerfile-language-server-nodejs-0.15.0.tgz
    sha256: 32ee93b98f43d8d60273019b7ed12a263593ba3a2308442ca7449d49676f480d
    sha512: ""
    signature: ""
build_dependencies: []
linux_dependencies: []
build:
    configure: []
    install: []
service: null
